# Generated by Django 2.2.4 on 2019-08-23 15:51

import P_Asset.apps.assets.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_asset', models.CharField(blank=True, max_length=100)),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('merk', models.CharField(blank=True, max_length=100)),
                ('tahun_pembuatan', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), P_Asset.apps.assets.models.max_value_current_year])),
                ('harga', models.FloatField(blank=True, null=True)),
                ('tgl_beli', models.DateTimeField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('surat_kepemilikan', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('google_places_id', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Category')),
            ],
        ),
    ]
