# Generated by Django 2.2.4 on 2019-08-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EP', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='kode_field',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='EP.FieldEP'),
        ),
    ]
