# Generated by Django 2.2.4 on 2019-08-23 17:23

import P_Asset.apps.assets.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assets', '0003_asset_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='user',
        ),
        migrations.AddField(
            model_name='asset',
            name='umur_asset',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='AssetMasyarakat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode_asset', models.CharField(blank=True, max_length=100)),
                ('nama', models.CharField(blank=True, max_length=100)),
                ('merk', models.CharField(blank=True, max_length=100)),
                ('tahun_pembuatan', models.PositiveIntegerField(default=2019, validators=[django.core.validators.MinValueValidator(1984), P_Asset.apps.assets.models.max_value_current_year])),
                ('umur_asset', models.CharField(blank=True, max_length=100)),
                ('harga', models.FloatField(blank=True, null=True)),
                ('tgl_beli', models.DateTimeField(blank=True, null=True)),
                ('lokasi', models.CharField(blank=True, max_length=100)),
                ('deskripsi', models.TextField(blank=True)),
                ('foto', models.ImageField(blank=True, upload_to='')),
                ('surat_kepemilikan', models.TextField(blank=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('google_places_id', models.CharField(blank=True, max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.Category')),
                ('owner', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
