# Generated by Django 2.2.4 on 2019-08-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0006_auto_20190824_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='jenis_sewa',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
