# Generated by Django 2.2.4 on 2019-08-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0008_auto_20190824_1955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='umur_asset',
            field=models.FloatField(blank=True, max_length=100),
        ),
    ]
